### ISSUE TITLE
Hacktoberfest: Video caption search demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-text-search-video-captions#1]
This is the tracker for polishing the “Video caption search” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [ ]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [ ]  Fixes for any of the identified issues 
    - [ ] <-- List any identified issues here (e.g., data ingestion, dataset issue, search, back-end/API, front-end) -->
- [ ]  Update README to include:
    - [x] Short description
    - [x] used technology
        - [ ] used Weaviate modules/ML models
    - [x] demo video
    - [x] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [ ] Dataset license if applicable
- [ ] Possible improvements/enhancements
    - [ ] Add progress bar to import file
    - [ ] Option to generate transcripts from video directly (e.g. with Whisper / wav2vec) (claimed by @Shubham05122002)
    - [ ] Add generative search to answer questions from search results (claimed by @Shubham05122002)
    - [ ] Generate video summary (claimed by @Shubham05122002)
    - [ ] Translation (for input or output)
    - [ ] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point)
    - [ ] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview) (claimed by @pranavjoy18)
        - [ ] After Weaviate release 1.22: swap out preview image

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by Shubham05122002** [comment]
I am interested in contributing to the task "Generate video summary" , "Add generative search to answer questions from search results" and "Option to generate transcripts from video directly (e.g. with Whisper / wav2vec)".

**Comment by iamleonie** [comment]
Thank you @Shubham05122002 for volunteering. Please don't hesitate to reach out via our Slack or forum discussions if you have any questions.

**Comment by Shubham05122002** [comment]
Sure

**Comment by pranavjoy18** [comment]
Hi @iamleonie , I am interested in taking up the task to convert to the new Weaviate Python Client

**Comment by iamleonie** [comment]
Hi @pranavjoy18, thank you for volunteering to work on the conversion to the new Weaviate Python client.
Let's align with @Shubham05122002 to avoid merge conflicts later since the conversion to the new Python client are quite big changes.

I see a few options here on how we could approach this:
1. @pranavjoy18 could make their changes first, and @Shubham05122002 could pull these changes into theirs and continue working with the new Python client
2. @pranavjoy18 Could help convert @Shubham05122002's changes to the new Python client after @Shubham05122002's changes are available

I'm open to different approaches.

Please align and let me know how you would like to proceed. :) 

You can use our community Slack to discuss as well.

**Comment by pranavjoy18** [comment]
Yea I am open to both of the approaches, depending on how long it will take @Shubham05122002 to get done. If its going to take him a bit of time on coming up with their feature, I could follow the approach #1 , else if @Shubham05122002 is underway with his changes , I would as well wait for them to make thier PR post which I could migrate the entire codebase. 

What say @Shubham05122002  ?

Also @iamleonie apart from the blog is their any detailed API reference page for the new Client ?

**Comment by Shubham05122002** [comment]
I might take a bit of time implementing them, so if @pranavjoy18 will take less time then we  can follow approach #1 else both of us could work on the tasks together(approach #2).Just let me know.

**Comment by pranavjoy18** [comment]
Yea cool I guess I can work on approach #1 then. Will finish it ASAP

**Comment by iamleonie** [comment]
Hi @Shubham05122002 , @pranavjoy18,
to get a better overview for new contributors of which tasks already have people working on them I added your names to some tasks in the issues description.

Kindly, review if my understanding is correct and please let me know if I need to change something. Also, if you want to switch to a different task, don't hesitate to ping me and we will "unclaim" the task :)

**Comment by Shubham05122002** [comment]
Sure

**Comment by Shubham05122002** [comment]
@pranavjoy18 can you please update me on how much more time will it take?

**Comment by pranavjoy18** [comment]
I am done with rewriting of the add_data.py file into the new python client , I'm facing a bunch of issues in the execution of index.js and am stuck in resolving them

**Comment by iamleonie** [comment]
Hi @pranavjoy18,
Please let us know if you require any assistance with resolving the issues. 
Did the demo run without issues before you made any changes?

**Comment by pranavjoy18** [comment]
Yea @iamleonie the demo was running without any issues before the changes were made

**Comment by iamleonie** [comment]
Ok, that's great to hear, @pranavjoy18. 
Please feel free to push your branch if you'd like assistance resolving the issues - but no pressure :)

**Comment by iamleonie** [comment]
Hey, I wanted to quickly check in with you two as it's the last week of Hacktoberfest.

@Shubham05122002 If your changes are ready to go, we could add yours first and Pranav's changes later.

@pranavjoy18 If you're still facing issues, we're happy to help you out in our [Community Slack](https://weaviate.io/slack) in the #hacktoberfest channel.

**Comment by Shubham05122002** [comment]
I have yet not started as we were following approach #1. I have an outline of the things I need to do so it should not take much time in implementing them. I am waiting for @pranavjoy18 pull request.

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
